services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./output_videos:/app/output_videos
      - ./.env:/app/.env
    environment:
      - NGROK_BASE_URL=${NGROK_BASE_URL}
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - ENABLE_NGROK=false
      - NGROK_MAX_RETRIES=1
      - NGROK_RETRY_DELAY=1
      - MAX_QUEUE_SIZE=10
      - RATE_LIMIT_PER_MINUTE=5
      - CACHE_EXPIRY_HOURS=24
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MAX_PARALLEL_RENDERINGS=4
    restart: unless-stopped
    # Add support for multi-processing by increasing resources
    deploy:
      resources:
        limits:
          cpus: '0'  # Use all available CPUs
          memory: 8G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s